### ISSUE TITLE
Long event names are getting cut on events page

### ISSUE THREAD

**Issue by otbe** [boyney123/eventcatalog#100]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

For example
<img width="368" alt="Screenshot 2022-01-22 at 14 11 19" src="https://user-images.githubusercontent.com/3391052/150639891-01ea2ee9-b487-4e31-8160-d550cbdaa910.png">

### Steps to reproduce

Having really long event names :)

### Expected behavior

Thats a really good question. Im not quite sure maybe we should break them and continue on the next line.

### Actual behavior

Its getting cut off by the event cards.

### Your environment

- EventCatalog version used: 0.0.12

**Comment by boyney123** [comment]
Thanks @otbe , should be fixed in `@eventcatalog/core@0.0.14` ⭐️

**Comment by boyney123** [comment]
closing issue as fixed in `@eventcatalog/core@0.0.14` 👍
