### ISSUE TITLE
Scrolling on the 3D graph page is kinda broken

### ISSUE THREAD

**Issue by fmvilas** [boyney123/eventcatalog#101]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Since scroll is used to zoom in/out the 3D graph, if I try to scroll to the footer, I can't because it "thinks" I want to zoom out. Same if I manage to get to the footer and want to scroll back up.

### Steps to reproduce

Go to the 3D graph and try scrolling past the graph (e.g., the footer).

### Expected behavior

I can easily scroll up and down without zooming in/out.

### Actual behavior

It zooms in/out and doesn't let me scroll.

### Your environment

- EventCatalog version used: demo online
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Latest Firefox.
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Latest Mac OS X.

**Comment by fmvilas** [comment]
I think one elegant way to solve this would be to require having a key pressed to zoom in/out. Like you'd do with embedded Google Maps.

**Comment by boyney123** [comment]
Been open awhile, going to close this, if anyone fancies picking this up feel free.
