### ISSUE TITLE
Some css is lost during production build

### ISSUE THREAD

**Issue by otbe** [boyney123/eventcatalog#118]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

If we run `npm run build` a production build&export will be generated. This works quite nice except for some css classes.

Example would be `<Admonition type="warning"/>`. In dev mode you will get a nice little yellow box, in the exported version its just a gray box. My assumption would be the class is somehow eliminated by DCE.

### Steps to reproduce

Use `<Admonition type="warning"/>` somewhere and export the catalog.

### Expected behavior

Box should be still yellow

### Actual behavior

Its just gray :D

### Your environment

- EventCatalog version used: 0.1.1

**Comment by boyney123** [comment]
Thanks @otbe 

Yeah found the issue, tailwind is purging the CSS and as they are dynamic it does not know how to handle these and removed the classes from css.

Got a fix incoming

**Comment by boyney123** [comment]
Fixed in #127 127
