### ISSUE TITLE
missing comma on eventbridge docs

### ISSUE THREAD

**Issue by tavelli** [boyney123/eventcatalog#142]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

missing comma here:

https://www.eventcatalog.dev/docs/api/plugins/@eventcatalog/plugin-doc-generator-amazon-eventbridge#installation-and-usage

`secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY`

**Comment by boyney123** [comment]
Thank you for the contribution and fix to the docs @tavelli
