### ISSUE TITLE
Eventbridge plugin rules and targets incomplete

### ISSUE THREAD

**Issue by Muthuveerappanv** [boyney123/eventcatalog#144]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When running the eventbridge generator, all events get documented as expected. But the rules and targets, do not get published to the document as expected. Only the last event in the events list is published. 

### Steps to reproduce

1. setup the asyncgenerator with eventrbridge plugin
2. make sure there are more than one event with rules and triggers for each
3. run `npm run generate`
4. observer that not all event documentation will have rules and targets (only one would have it)

### Expected behavior

All events with rules and triggers should get documented in the `index.md` files

### Actual behavior

Not all event documentation will have rules and targets (only one would have it)

### Your environment

- EventCatalog version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS)
![Screen Shot 2022-01-28 at 5 18 58 PM](https://user-images.githubusercontent.com/33663725/151629582-017f2bc0-b00c-4113-9a9c-1222858aee8c.png)
:

**Comment by boyney123** [comment]
Hi @Muthuveerappanv ,

Thanks for raising the issue.

I'm trying to replicate locally. To help me understand are you using both `asyncapi` geneartor and `eventbridge` generator?

What happens if you just use the `eventbridge` generator out of interest, do your targets work OK?

**Comment by boyney123** [comment]
Ah managed to replicate the issue and see your fix too, will review it, thanks!

**Comment by boyney123** [comment]
Should be fixed in `0.0.5` if you want to give that ago when you can? Let us know how you get on :)

**Comment by Muthuveerappanv** [comment]
works fine in 0.0.5, closing this issue.
