### ISSUE TITLE
pages and events index.html generation

### ISSUE THREAD

**Issue by tavelli** [boyney123/eventcatalog#156]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

i'm not sure where this is configured but when build is run the index.html pages for events and services are not being placed correctly in their respective subfolders. instead they are created at root of site.  this causes site to break if you try to refresh or deeplink to `/events/` and `/services/` paths which are used in main site navigation.

### Steps to reproduce

1. run `npm run build` commands
2. check `/out` folder

### Expected behavior

/out/events/index.html
/out/services/index.html

### Actual behavior

/out/events.html
/out/services.html

**Comment by boyney123** [comment]
Thank you for raising the issue @tavelli.

@otbe @thim81 this is what we were talking about with the `trailingSlash` stuff?

**Comment by thim81** [comment]
Correct, if you set 'trailingSlash:true', the out folder will contain proper index.html pages. 

https://www.eventcatalog.dev/docs/api/eventcatalog-config#trailingslash

**Comment by boyney123** [comment]
Yeah just replicated the issue, @tavelli if you add the trailingSlash to your config it should work 👍🙏

Can you let us know if it does and we will close the issue, thanks!

**Comment by tavelli** [comment]
thanks yes! i was going to suggest to make it the default but it looks like you already took care of it 👍 👍
