### ISSUE TITLE
Support Versions for Services

### ISSUE THREAD

**Issue by boyney123** [boyney123/eventcatalog#159]
Like `events` it would be nice if we could version the services too.

Services will adapt over time and would be great to give users the ability to version them like we can events.

Some ideas
- Add version to the service markdown files
- Implement the `versioned` directory like events
- New page that loads the services

**Comment by lyndsysimon** [comment]
This is a duplicate of #90.

**Comment by boyney123** [comment]
Thanks @lyndsysimon !
