### ISSUE TITLE
JSON diff in chnagelog view can be larger than viewport

### ISSUE THREAD

**Issue by otbe** [boyney123/eventcatalog#183]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

I recently noticed that if you have a longer description somewhere in the JSON schema it will expand the "diff" view infinitely.

### Steps to reproduce

<img width="1497" alt="Screenshot 2022-02-07 at 19 05 57" src="https://user-images.githubusercontent.com/3391052/152846510-5d0b7279-06f1-42bb-bc08-09ed3b67537c.png">

Repro: https://github.com/otbe/eventcatalog-playground

### Expected behavior

It should wrap the lines at some point I guess

### Actual behavior

You have to scroll horizontally a lot :D

### Your environment

- EventCatalog version used: 0.1.14

**Comment by donaldpipowitch** [comment]
This is not officially supported by `diff2html`, see https://github.com/rtfpessoa/diff2html/issues/99. There is a workaround however by applying those styles:

```
.d2h-code-line, .d2h-code-line-ctn {
  white-space: pre-wrap;
}
```

Lines will break correctly now and the only limitation is (afaik) that line heights will not by in sync in the side-by-side view. But it will make the diff instantly more readable.

@boyney123, would you be fine with this "workaround"? If yes, I'd create a Merge Request.

**Comment by boyney123** [comment]
Thank you @donaldpipowitch , yeah feel free to make the Merge Request 👍 🙇
