### ISSUE TITLE
Visualiser does not persist new source to query params

### ISSUE THREAD

**Issue by otbe** [boyney123/eventcatalog#192]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

The new visualiser allows to jump in via a pre selected source (event/service) via query params but while switching between events/service it does not persist the selected entity to the query params.

It would be nice to do this in order to be able to share a link to a proper view.

### Steps to reproduce

- go to visualiser
- select something
- query params are not added/updated

### Expected behavior

Should persist it

### Actual behavior

Does not persist it.

### Your environment

- EventCatalog version used: 0.1.17
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

**Comment by boyney123** [comment]
Fixed with #224 👍
