### ISSUE TITLE
Visualiser produces UI glitch

### ISSUE THREAD

**Issue by otbe** [boyney123/eventcatalog#193]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

If you have longer event names the visualiser tends to produce nodes that overlap each other.
Interestingly this only happens if you switch between events/service, if you jump in via query params the result looks good.

### Steps to reproduce

Have events with very long names.
See https://github.com/otbe/eventcatalog-playground/tree/visualiser

### Expected behavior

Should render a nicely view in every case :)

### Actual behavior

Direct access via query params:
<img width="1728" alt="Screenshot 2022-02-09 at 21 40 37" src="https://user-images.githubusercontent.com/3391052/153286650-c201f10f-5dd9-414b-9db0-570c650d5c27.png">

Selected via menu
<img width="1727" alt="Screenshot 2022-02-09 at 21 40 46" src="https://user-images.githubusercontent.com/3391052/153286653-be3fed3f-31bc-4f94-b711-6a4f0ffb0d24.png">

This is a simple example. In our case it also happens that nodes overlaps each other more than half.

### Your environment

- EventCatalog version used: 0.1.17

**Comment by boyney123** [comment]
Thanks @otbe 

Is this still an issue? I think the node graph logic was changed recently, wonder if that has been fixed? Are you still seeing the issue in your Catalog?

**Comment by boyney123** [comment]
I believe this is fixed in [@eventcatalog/core@0.2.8](https://github.com/boyney123/eventcatalog/releases/tag/%40eventcatalog%2Fcore%400.2.8)

Going to close for now @otbe  (think you are happy with it from what I understand over on Discord).

Any more issues feel free to raise 🙏👍, thanks for raising this one
