### ISSUE TITLE
Adding domain support in eventcatalog utils

### ISSUE THREAD

**Issue by boyney123** [boyney123/eventcatalog#221]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

It would be great to have domain support for the functions `writeEventToCatalog` and `writeServiceToCatalog`.

We could have extra option to the function `domain` if the name of the domain is given it will:

- Check to see if the domains folder has been created (create if not)
- Check to see if the domain folder inside has been created (create if not)
- Check to see if domain has required `index.md` file (create if not)
- Put event inside the domains events folder `/domains/{Your Domain}/events/{Domain Path}`

Same with services.

This would allow plugin authors the ability to create services,events easier within domains.

### Motivation

Making it easier for plugin authors to create events, services within eventcatalog into domains.

**Comment by mikaelvesavuori** [comment]
Related to this, a way of passing information on Service + Domain from for example an AsyncAPI schema could be:

```yaml
  title: MyService
  x-domain: SomeDomain
  x-service: MyService
```

**Comment by boyney123** [comment]
@dpwdec has done a great job adding this to the utils https://github.com/boyney123/eventcatalog/blob/master/packages/eventcatalog-utils/src/domains.ts

Going to close this issue for now, if we want any more we can add them as we go :)
