### ISSUE TITLE
Bad linking on Graph nodes

### ISSUE THREAD

**Issue by akhansari** [boyney123/eventcatalog#223]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

On a graph when clicking on an object the redirection is not correct when the event or the service is on a domain.

### Steps to reproduce

1. Go to a domain like https://app.eventcatalog.dev/domains/Shopping/
2. Click on AddedItemToCart on the Graph
3. Error 404 not found

### Expected behavior

Should be redirected to https://app.eventcatalog.dev/domains/Shopping/events/AddedItemToCart/

### Actual behavior

It's redirected to https://app.eventcatalog.dev/events/AddedItemToCart/

### Your environment

- EventCatalog version used: 0.2.6
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Chrome 89, Node.js 16.4
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 10

**Comment by boyney123** [comment]
Thank you for raising @akhansari 

We are aware of this problem, the way events > service models in EventCatalog link to each other does not lend itself to knowing domains from events > services very easily. 

It's something in my list to take a look at soon

**Comment by boyney123** [comment]
Thanks to @drub0y this is now fixed in the latest version of EventCatalog ♥️

Any other problems let us know, going to close this for now.
