### ISSUE TITLE
AsyncAPI Generator does not parse relative message paths correctly.

### ISSUE THREAD

**Issue by dpwdec** [boyney123/eventcatalog#238]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

The AsyncAPI Event Catalog generator does not correctly parse relative `$ref` file paths between APIs and message schemas. Instead it processes the `$ref` paths relative to the `.eventcatalog-core` folder.

### Steps to reproduce

1. Add an asyncapi file in a surface area folder (in this example called `docs` with a `$ref` to a message in a different location in that folder.
```yaml
# api_1.yaml
# --- snip ---
publish:
    message:
        $ref: ../../../schemas/message_2.yaml
```

3. Add the `$ref`'d message file.

2. Run the parser.

The final set up should look something like this, but the paths are arbitrary really, as long as it doesn't exactly match how `.eventcatalog-core` structure works. This is very likely in real life scenarios for API parsing considering there is no standard for organising the AsyncAPI files on a file system.
```
docs
├── spec
|   └── services
|       └── apis
|           └──api_1.yaml
|   
└── schemas
    └── message_2.yaml
```

### Expected behavior

The `$ref` paths are parsed relative to where the original AsyncAPI file is located.

### Actual behavior

The `$ref` path does not resolve correctly because these paths are parsed by the generator relative to the .eventcatalog-core folder. 

So for an actual surface area representation to be parsed correctly all of the relative `$ref` paths need to be updated before generation.

In the above example the path would have to change to `../docs/schemas/message_2.yaml` to come out of the `.eventcatalog-core` folder and down into the `spec/schemas` directory to find the correct message linked to this API.

### Your environment

- EventCatalog version used: 0.2.10
- EventCatalog pluging-doc-generator-asyncapi version used: 0.0.0-2022030192614
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS Catalina

**Comment by cthornhill** [comment]
FYI - the customer I want to target first for EventCatalog would like (at the CTO level) to adopt AsyncAPI as the policy guidance for the enterprise level. This particular customer has a policy approach that allows units inside the enterprise with internal IT governance (their own C level equivalents) and their "product lines" to use tech as they see fit inside "guard rails". For them, AsyncAPI will be the "Enterprise repo format" but as you know, that means that actual events can be done a wide number of ways. Hence I also have some longer term interest in seeing how this bug gets resolved and general interactions with AsyncAPI "play out" in the future.
