### ISSUE TITLE
Mermaid diagrams don't respect domains when clicking services / events

### ISSUE THREAD

**Issue by robertbennett1998** [boyney123/eventcatalog#239]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

When clicking on nodes within a mermaid diagram it tries to redirect you to the event / service however it doesn't respect the domain for that event / service.

![event catalog](https://user-images.githubusercontent.com/8798036/157831042-fce97bae-8697-4d09-9786-1ceae285382d.gif)

### Steps to reproduce

1. In a catalog with events and services that are in domains.
2. Add a mermaid diagram to a service or event that that refers to another event or service in the same or different domain.
3. Navigate to the mermaid diagram you just added.
4. Click on one of the nodes.

### Expected behavior

The redirection respects whether or not that event / service is in a domain.

### Actual behavior

You are redirected but the url doesn't respect the domain.

### Your environment

- EventCatalog version used: 0.2.9

**Comment by boyney123** [comment]
Hey @robertbennett1998 

Sorry for taken so long to get back.

This should now be fixed in 

```
- @eventcatalog/core@0.2.16
- @eventcatalog/types@0.1.4
```

Let me know if you continue to face the problems, going to close this assuming it works OK (works for me with latest)

**Comment by mantis7** [comment]
@boyney123  hi is this issue still exist? seems ok on docker, but not ok on AWS S3/cloudfront, I am using the latest version 1.2.5
