### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by justin-umesh** [boyney123/eventcatalog#250]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description
Not able to run 'npm run build' successfully after adding the plugin 'plugin-generator-amazon-eventbridge'

npm run build

> my-catalog@0.0.1 build
> eventcatalog build

> @eventcatalog/core@0.1.5 scripts:move-schema-for-download
> node scripts/move-schemas-for-download.js

> @eventcatalog/core@0.1.5 build
> next build && next export

Failed to compile.

./components/Sidebars/EventSidebar.tsx:39:43
**Type error: Type 'Service' is not assignable to type 'Key'.**

  37 |           <ul className="mt-2 leading-8">
  38 |             {producers.map((producer) => (
> 39 |               <li className="inline mr-1" key={producer}>
     |                                           ^
  40 |                 <Link href={`/services/${producer}`}>
  41 |                   <a className="relative inline-flex items-center rounded-full border border-gray-300 px-3 py-0.5">
  42 |                     <div className="absolute flex-shrink-0 flex items-center justify-center">
info  - Checking validity of types .Error: Command failed: 

### Steps to reproduce

npm run build

### Expected behavior

Build should be successfull

### Actual behavior

Build is getting failed.

### Your environment
eventcatalog.config.js configuration

module.exports = {
  title: 'EventCatalog',
  tagline: 'Discover, Explore and Document your Event Driven Architectures',
  projectName: 'Event Catalog',
  editUrl: '',
  trailingSlash: true,
  logo: {
    alt: 'EventCatalog Logo',
    // found in the public dir
    src: 'logo.svg',
  },
  footerLinks: [],
  users: [],
  generators: [
    [
      '@eventcatalog/plugin-doc-generator-amazon-eventbridge',
      {
        eventBusName: '', // your event bus name
        region: 'us-east-1', // your region
        registryName: 'discovered-schemas', // your registry normally "discovered-schemas"
        credentials: {
          accessKeyId: process.env.AWS_ACCESS_KEY_ID,
          secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
          sessionToken: process.env.AWS_SESSION_TOKEN // optional
        },
      },
    ],
  ],
}

**Comment by boyney123** [comment]
Hi @justin-umesh 

This should be fixed in version `@eventcatalog/core@0.2.14 ` if you would like to try?

**Comment by boyney123** [comment]
Closing this issue, if you have any other problems let me know :)
