### ISSUE TITLE
Links in NodeGraphs do not take domains into account

### ISSUE THREAD

**Issue by drub0y** [boyney123/eventcatalog#255]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Clicking on a node in a NodeGraph that shows services and events that belong to domains links to top-level `services` and `events` directories rather than `domains/<domain>/services` and `domains/<domain>/events` directories.

### Steps to reproduce

1. Create a domain
2. Add a service that produces an event
3. Click on the Visualizer
4. Click on the event created in step 2 that belongs to the domain
5. Get a 404 because it goes to `/events/<event-name>` rather than `/domains/<domain>/events/<event-name>`

### Expected behavior

Should navigate to the `/domains/<domain>/events/<event-name>` documentation.

### Actual behavior

Navigates to the `/events/<event-name>` resulting in a 404 not found.

### Your environment

- EventCatalog version used: 0.2.14

**Comment by drub0y** [comment]
I've got a PR coming to fix this shortly, just wanted to get it in as an Issue I can reference first.

**Comment by boyney123** [comment]
Thank you @drub0y  for the issues, PR and ideas, release going out now, going go close this issue. Any issues let me know :)
