### ISSUE TITLE
Plugins should render NodeGraphs over Mermaid graphs by default

### ISSUE THREAD

**Issue by boyney123** [boyney123/eventcatalog#260]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Mermaid was used at the start, but maybe we should consider removing it in favour of the NodeGraph to clean up the code.

### Motivation

Clean up code base

**Comment by JamesRamm** [comment]
Hi
Thanks for this wonderful project!
I am starting to explore introducing EventCatalog to my company. 
Just as a note on this issue; indeed the generated site is using NodeGraph, but the documentation still refers to Mermaid everywhere.

**Comment by boyney123** [comment]
Hey @JamesRamm , glad you like the project!

Yeah default graph is using NodeGraph but the plugins for AsyncAPI and EventBridge are still using Mermaid, I will update this ticket to address those.

**Comment by boyney123** [comment]
New release out for AsyncAPI parser and utils that will now default to NodeGraphs rather than Mermaid.
