### ISSUE TITLE
Allow "Getting Started" button to be removed / hide possibly with the flag

### ISSUE THREAD

**Issue by chotalia** [boyney123/eventcatalog#275]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

It would be helpful to have settings to remove the "Getting Started" button or 
have ability to modify it and if not defined do not show it.

### Motivation

In the production build, we want the front page to have minimal details.

**Comment by boyney123** [comment]
Thanks @chotalia ,

Releasing a new change now that will allow you to turn it off or change it to whatever you need :)

**Comment by boyney123** [comment]
New fields added to EventCatalog config file.

`PrimaryCTA` and `SecondaryCTA` : https://www.eventcatalog.dev/docs/api/eventcatalog-config#primaryCTA

Update to the latest eventcatalog `core`, `types` to get it worked.

Thanks for the idea, hope it helps.

**Comment by chotalia** [comment]
Thank you @boyney123
