### ISSUE TITLE
Generated script/resource urls are rooted, can they be relative?

### ISSUE THREAD

**Issue by damianh** [boyney123/eventcatalog#282]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Lovely project ❤️ 

The urls generated for scripts etc are rooted urls. That is they start with `/` e.g.: <script src="/_next/static/chunks/webpack-203a6ceb71ee99ad.js">

However if the index.html is not hosted in the web side root, e.g. "http://example.com/event-catalog/index.html", loading the page will result in 404s and a broken site.

### Steps to reproduce

1. Buld site.
2. Host on a path, not on a root.

### Expected behavior

Urls should be non-rooted / relative. 

e.g. <script src="_next/static/chunks/webpack-203a6ceb71ee99ad.js"

Note, no `/` at start.

### Actual behavior

![image](https://user-images.githubusercontent.com/57436/172415253-3b7f602a-b0d6-4692-81f0-ccaad3803fd4.png)

### Your environment

- EventCatalog version used: "@eventcatalog/core": "0.2.19"
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node v14.18.0
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Win 11.

**Comment by dytyniuk** [comment]
Hello @damianh and thank you for noticing this.

Despite I'm not a maintainer of the project, the problem resonates with me - I also had an idea to host the documentation site behind a path.

While "the fix" could be quite straightforward, the problem is that the generated website replicates a directory structure of events, domains and services. So, tracking how "deep" a concrete page is from the "root" would be challenging, IMHO.

Could it be an idea to introduce a configuration parameter in the `eventcatalog.config.js`, that is used to generate `src` attributes' values?

Just thinking out loud here 😊

**Comment by dytyniuk** [comment]
Hi @damianh

> Not sure why the directory structure is a problem - if links are relative it should "just work". Am I missing something?

Let's look at 2 pages from the [app.eventcatalog.dev](https://app.eventcatalog.dev):
* `https://app.eventcatalog.dev/domains/Orders/events/OrderRequested/`
* `https://app.eventcatalog.dev/events/PaymentProcessed/`

We have 2 events described at a different depth relating to the root of the build:
* the `OrderRequested` is 4 directories "down"
* while the `PaymentProcessed` is only 2 directories "down"

This page's depth has to be "tracked" to generate correct relative values for the `src` attribute. The thing goes even wilder if we bring versioned events to the table.

On the other hand, the "deploy time" and "build time" problem you have described is a valid one, true. In such a case, the only solution sitting at the top of my head is a CDN - static asses are served from the CDN, which domain is "baked" into the build 🤷‍♂️

**Comment by dytyniuk** [comment]
Hi @damianh 

I was checking some documentation and found, that the "build time" approach to tackle path-based deployment is a sort of a standard one. Examples:
* Hugo has the [`baseurl` configuration option](https://gohugo.io/getting-started/configuration/#baseurl)
* MkDocs uses the [`site_url` option](https://www.mkdocs.org/user-guide/configuration/#site_url) for the same purpose

As you can see, this is a standard approach for such a case.

**Comment by dytyniuk** [comment]
@damianh good morning. Look, there's an options for this already -- https://www.eventcatalog.dev/docs/api/eventcatalog-config#basepath

I hope, that helps

**Comment by damianh** [comment]
Will take a look @dytyniuk . Ty.

**Comment by boyney123** [comment]
Thanks @dytyniuk for helping out on this one 🙏🙇

@damianh will close for now, if you have any more issues feel free to reopen :).
