### ISSUE TITLE
crash - during runtime, just getting started

### ISSUE THREAD

**Issue by zbenmo** [boyney123/eventcatalog#311]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

 1 of 1 unhandled error
Server Error
TypeError: fnv.fast1a52hex is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
hash
file:///home/oren/eventcatalog/my-catalog/node_modules/@stoplight/json-schema-viewer/index.mjs (145:38)
getNodeId
file:///home/oren/eventcatalog/my-catalog/node_modules/@stoplight/json-schema-viewer/index.mjs (153:12)
<unknown>
file:///home/oren/eventcatalog/my-catalog/node_modules/@stoplight/json-schema-viewer/index.mjs (593:20)
processChild
file:///home/oren/eventcatalog/my-catalog/node_modules/react-dom/cjs/react-dom-server.node.development.js (3353:14)
resolve
file:///home/oren/eventcatalog/my-catalog/node_modules/react-dom/cjs/react-dom-server.node.development.js (3270:5)
ReactDOMServerRenderer.render
file:///home/oren/eventcatalog/my-catalog/node_modules/react-dom/cjs/react-dom-server.node.development.js (3753:22)
ReactDOMServerRenderer.read
file:///home/oren/eventcatalog/my-catalog/node_modules/react-dom/cjs/react-dom-server.node.development.js (3690:29)
Object.renderToString
file:///home/oren/eventcatalog/my-catalog/node_modules/react-dom/cjs/react-dom-server.node.development.js (4298:27)
renderDocument
file:///home/oren/eventcatalog/my-catalog/node_modules/next/dist/server/render.js (736:47)
Object.renderToHTML
file:///home/oren/eventcatalog/my-catalog/node_modules/next/dist/server/render.js (819:34)

### Steps to reproduce

Install on Windows/WSL/Ubuntu/zsh

oren@DESKTOP-11JEIEO ~ % node -v
v16.18.0
oren@DESKTOP-11JEIEO ~ % npm -v
8.19.2
oren@DESKTOP-11JEIEO ~ % yarn --version
1.22.19

Then running, and when available clicking once on an event to examine the (fields?)

### Expected behavior

no bug

### Actual behavior

bug - crash

### Your environment

- EventCatalog version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):Install on Windows/WSL/Ubuntu/zsh

oren@DESKTOP-11JEIEO ~ % node -v
v16.18.0
oren@DESKTOP-11JEIEO ~ % npm -v
8.19.2
oren@DESKTOP-11JEIEO ~ % yarn --version
1.22.19

**Comment by boyney123** [comment]
Thanks, yeah looks like a release of a spotlight package we are using has broken the build. Will patch and let you know when it's ready, thank you for raising it!

**Comment by boyney123** [comment]
Thanks @zbenmo , should be fixed now if you try again, let me know if it works! Thanks
