### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by youbihi** [boyney123/eventcatalog#319]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

I am not able to build a docker image of the event catalag.

First bug:
![Capture d’écran 2022-11-03 à 16 48 56](https://user-images.githubusercontent.com/5676321/199769638-2c048ff3-e1d7-45a7-8d42-efd03612c58e.png)

second bug:
![Capture d’écran 2022-11-03 à 16 51 11](https://user-images.githubusercontent.com/5676321/199769702-50a968e7-3afc-4c97-8423-eb2752f7efdb.png)

### Steps to reproduce

docker build -t event-catalog

### Expected behavior

should build a docker image

### Actual behavior

error when building the docker image

### Your environment

- EventCatalog version used: 0.0.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): nodeJS : v16.13.2
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Mac Os
- Docker Desktop mac:  Engine: 20.10.12 Compose: v2.2.3 Credential Helper: 0.6.4 Kubernetes: v1.22.5

**Comment by boyney123** [comment]
Hi @youbihi ,

@mikaelvesavuori found a fix for us over on #320, just releasing it now, so hopefully time you read this should be live.

Try again and let us know.

Going to close for now.
