### ISSUE TITLE
Incorrect display in the visualiser when displaying all services and events

### ISSUE THREAD

**Issue by mm98hub** [boyney123/eventcatalog#339]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

In my opinion there is a bug in the global display in visualiser, when each event is displayed as an input in at most one service, regardless of how many services actually consume that event. To demonstrate the problem I will use simple system with 3 events (A, B and AB) and 2 services (Service A and Service B).  Service A consumes A and AB. Service B consumes B and AB. So both services consume event AB. Note that this problem doesn’t exist when events and services are viewed individually.

### Steps to reproduce

1. Create three events A, B and AB
2. Create Service A that consumes events A and AB
3. Create Service B that consumes events B and AB
4. Run event catalog and take a look at all events and services displayed in visualiser.

### Expected behavior

Event AB is displayed as input to both services (Service A and Service B).

### Actual behavior

It’s obvious that the problem exists in the part where services are represented, because it is not shown that the service A consumes event AB. 
<img width="1408" alt="global-display-bug" src="https://user-images.githubusercontent.com/101356487/211337620-3c6ad53c-2ce4-4664-8b97-b2e484fbb334.png">

### Your environment

- EventCatalog version used: 0.6.3
- Environment name and version:  Chrome 108, Node.js 14.18.12
- Operating system and version: macOS Sierra 10.13.6

**Comment by boyney123** [comment]
Hey @mm98hub , 

Let me know if this is still an issue with the latest version, some minor changes have been made, going to close for now unless you see the issue

**Comment by letrunghieu** [comment]
This bug is still happens with version 1.1.1

#456

**Comment by s1mrankaur** [comment]
+1. Still an issue
