### ISSUE TITLE
After using `npm run dev` an exports error pops up.

### ISSUE THREAD

**Issue by DevSlashRichie** [boyney123/eventcatalog#347]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

After a clean installation and running `npm run dev` the platform crashes by the following errror:
![image](https://user-images.githubusercontent.com/8129679/219510184-fcf2a161-be63-4524-a635-debd6c8ee7e6.png)

### Steps to reproduce

Run `npm run dev`

try clicking on `explore events`

### Expected behavior

Open the page for exploring events.

### Actual behavior

![image](https://user-images.githubusercontent.com/8129679/219510184-fcf2a161-be63-4524-a635-debd6c8ee7e6.png)

```
SyntaxError: Named export 'o' not found. The requested module './mermaid.95cd9c8e.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './mermaid.95cd9c8e.js';
const { o } = pkg;
```

### Your environment

- EventCatalog version used: latest (0.6.4)
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node: 18.12.1
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Ubuntu 22.04 LTS x86_64

**Comment by PaGury** [comment]
Exact same problem for me :+1:

**Comment by boyney123** [comment]
Thanks, for raising this, will fix this in the build.

**Comment by boyney123** [comment]
Thanks fixed in latest build :)
