### ISSUE TITLE
Docker container, anyone?

### ISSUE THREAD

**Issue by reza8iucs** [boyney123/eventcatalog#380]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

I have made several attempts to build a docker container from this app and ship it to various platforms locally and in the cloud with no lock. Has anyone been able to containerize this app? I get "stream timeout" when building and run it in Docker container and I get this when i deploy it to various container based services in Azure and AWS. 

### Steps to reproduce

use the included docker file to containerize this app.

### Expected behavior

app should work as if it's running using yarn dev or npm start dev

### Actual behavior

I get the following error both in docker container and in the cloud "stream timeout"

### Your environment

- EventCatalog version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

**Comment by mfreeman451** [comment]
I can't get the docker image to build at all on Ubuntu

**Comment by boyney123** [comment]
Will close this for now, if you still find issues please raise a new ticket and will have a look, I managed to replicate issues and the new file fixes them, thanks for raising the issue.
