### ISSUE TITLE
integrate with Docusaurus

### ISSUE THREAD

**Issue by ryan1cranetime** [boyney123/eventcatalog#383]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Is there a way to integrate EventCatalog in docusaurus?

### Motivation

We are using docusaurus for all of other documentation.

**Comment by boyney123** [comment]
Hey @ryan1cranetime 

No way at the moment to integrate the two really, only thing I can think of is to host the two separate then link to each other.

EventCatalog is influenced heavily on docusaurus architecture, so might be something you can do if you dive deeper.

Going to close the issue for now, unless you want to know more or explore deeper.
