### ISSUE TITLE
Expose more OpenAPI component options

### ISSUE THREAD

**Issue by kernwig** [boyney123/eventcatalog#387]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

The default output of the <OpenAPI/> (SwaggerUI under the hood) is to require clicking on every property individually to expand it. I find this exasperating; an entire level should expand at once.

[SwaggerUI](https://www.npmjs.com/package/swagger-ui-react) has options to control this, they just need to be exposed: `docExpansion` and `defaultModelExpandDepth`.

The options `defaultModelRendering` and `displayOperationId` also look useful.

(I'd offer a PR, but simply `git clone` and `npm install` fail for me.)

### Motivation

Allow for further customization to project needs.

**Comment by boyney123** [comment]
Thanks @kernwig , I have made a feature change to allow this, thanks for the idea. Going live now.

**Comment by kernwig** [comment]
Thank you. :-) I ended up using 

`<OpenAPI showTitle="false" defaultModelExpandDepth="2" defaultModelRendering="model"/>`

Appreciate the Swagger UI update as well.
