### ISSUE TITLE
EventBridge generator: Retrieve more results

### ISSUE THREAD

**Issue by cgabard** [boyney123/eventcatalog#425]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

It seems the current implementation of EventBridge catalog only pull one page of events. As we have more than 100 events on our discovered catalog, we do not gather all and it does not seems to have way to retrieve alls.

### Motivation

Be able to retrieve all our event from eventbridge

**Comment by boyney123** [comment]
Thank you @cgabard , this is now merged and updated in the latest version of the plugin.
