### ISSUE TITLE
EventBridge generator: Allow filter events

### ISSUE THREAD

**Issue by cgabard** [boyney123/eventcatalog#426]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

On EventBridge generator, it would be great if we can filter the events.
There is two way to do this:
 - using AWS SDK "event type prefix" parameter so we can at list list the event type prefix we want to retrieve
 - A JS side function

In theory, both can fit our need but currently we can not use this project because of this (and because of the "only 100 events" limitation)

### Motivation

In my company we have a global and general event bus that aggregate all events before dispatching them. Beside aggregating all services types, it also aggregate them from all environment.

The environment is specified on the source so we have events like "service1.production@email-send" or "service2.dev@contract-validated".

However it generate a catalog with lot of events. Beside the fact that we need then to fetch more than 100 events (#425 ), we would need to be able to filter result to only retrieve "production" ones (or dev ones).

**Comment by cgabard** [comment]
If you agree on adding parameter for this problem, I can likely do a PR for this one and #425 at some point. Please let me know

**Comment by boyney123** [comment]
Yeah I think some config to the plugin would be great, also the 100 limit is interesting, I guess the plugin does not loop around, two seperate PR would be great for these!

**Comment by cgabard** [comment]
Thanks for your feedback. I am on another subject for now but this one will come back soon. I will try to do the PR when possible if no one did it before but not sure when for now. I will keep you updated.

**Comment by cgabard** [comment]
So, I had a bit of time this morning, I prepared a PR: https://github.com/boyney123/eventcatalog/pull/457

**Comment by boyney123** [comment]
Thank you @cgabard , this is now merged and updated in the latest version of the plugin.

**Comment by cgabard** [comment]
Thanks to you, your reactivity and welcoming on the project contribution.

Le dim. 12 nov. 2023, 10:16, David Boyne ***@***.***> a
écrit :
