### ISSUE TITLE
Toggling a badge filter causes the service list to be incorrect

### ISSUE THREAD

**Issue by autodidaddict** [boyney123/eventcatalog#429]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

In the services list, toggling a badge filter on and off multiple times causes the services list to grow indefinitely.l

### Steps to reproduce

I start out with a list of services, some with a badge and some without. I click to filter by the badge and the ones I expect to vanish go away. When I then uncheck the box, one of the services previously hidden has come back twice.

By clicking and unclicking the badge filter checkbox, I can cause the list of services to grow infinitely when putting back the previously excluded items.

### Expected behavior

I expect the list to have two states - filtered and unfiltered. I should not see duplicate services.

### Actual behavior

Services are duplicated and the list grows without a cap

### Your environment

- EventCatalog version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Arc and Chrome, both latest
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): MacOS latest

**Comment by autodidaddict** [comment]
After further experimentation it seems like this only occurs when a service or event has the same name in 2 different domains. This doesn't happen with unique entity names.

**Comment by boyney123** [comment]
Thank you @autodidaddict , I have fixed this in #438 

Will get this released 🚀
