### ISSUE TITLE
Async API 3.0 Support

### ISSUE THREAD

**Issue by zbigniew-malcherczyk-tg** [boyney123/eventcatalog#467]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Async API recently released version 3.0 and all the Async API tools already are compatible with it. That means we should be able to seamlessly upgrade the Async API event catalog generator plugin.

**Comment by boyney123** [comment]
This has now been added https://github.com/boyney123/eventcatalog/pull/465
