### ISSUE TITLE
Cannot run build step  - Attempted import error: 'useSyncExternalStore' is not exported from 'react' (imported as 'React2').

### ISSUE THREAD

**Issue by cteer-everquote** [boyney123/eventcatalog#468]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Following error occurs when creating the project and running `npm run build`
- Happens on various different versions
- Have tried solving version conflicts using overrides
- `npm run dev` works fine
- Happens locally and in GHA
```
info  - Linting and checking validity of types...
info  - Creating an optimized production build...

warn - The `purge`/`content` options have changed in Tailwind CSS v3.0.
warn - Update your configuration file to eliminate this warning.
warn - https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

warn - As of Tailwind CSS v3.3, the `@tailwindcss/line-clamp` plugin is now included by default.
warn - Remove it from the `plugins` array in your configuration to eliminate this warning.

warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
warn - Change `darkMode` to `media` or remove it entirely.
warn - https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
Failed to compile.

../node_modules/swagger-ui-react/node_modules/react-redux/dist/react-redux.mjs
Attempted import error: 'useSyncExternalStore' is not exported from 'react' (imported as 'React2').

Import trace for requested module:
../node_modules/swagger-ui-react/node_modules/react-redux/dist/react-redux.mjs
../node_modules/swagger-ui-react/swagger-ui-es-bundle-core.js
../node_modules/swagger-ui-react/index.mjs
./components/Mdx/OpenApiSpec.tsx


> Build failed because of webpack errors
Error: Command failed: cross-env PROJECT_DIR='/home/runner/work/event-catalog/event-catalog' npm run build
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Command.<anonymous> (/home/runner/work/event-catalog/event-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:60:5)
    at Command.listener [as _actionHandler] (/home/runner/work/event-catalog/event-catalog/node_modules/commander/index.js:922:31)
    at Command._parseCommand (/home/runner/work/event-catalog/event-catalog/node_modules/commander/index.js:1503:14)
    at Command._dispatchSubcommand (/home/runner/work/event-catalog/event-catalog/node_modules/commander/index.js:1443:18)
    at Command._parseCommand (/home/runner/work/event-catalog/event-catalog/node_modules/commander/index.js:1460:12)
    at Command.parse (/home/runner/work/event-catalog/event-catalog/node_modules/commander/index.js:1292:10)
    at run (/home/runner/work/event-catalog/event-catalog/node_modules/@eventcatalog/core/bin/eventcatalog.js:115:7) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 2[38](https://github.com/cteer-everquote/event-catalog/actions/runs/7464685588/job/20312192621#step:5:39)2,
  stdout: null,
  stderr: null
}
```

### Steps to reproduce

npx @eventcatalog/create-eventcatalog@latest catalog
npm run build

### Expected behavior

NextJS build succeeds and produces output

### Actual behavior

Above error occurs

### Your environment

- EventCatalog version used: latest (1.1.0) and 1.0.1
- Environment name and version (Node v20.4.0 locally, Node 18 in GHA):
- Operating system and version (Mac M1 chip Ventura 13.6.3):

**Comment by danielcastill0** [comment]
I am having this issue too, same conditions as above :)

**Comment by CTeer458** [comment]
I've tried various older versions too and I'm having the same issue

**Comment by danielcastill0** [comment]
@boyney123 sorry, maybe you could help us to understand what happens here?

**Comment by explorer14** [comment]
Facing this problem as well since Jan12th 9PM GMT (both on my dev workstation and also on Azure Pipelines CI builds). Last successful build for me was on Jan 6th 12AM GMT using version 1.1.1. Dependencies foobarring?

**Comment by mnlc** [comment]
I had the same issue. Just start and build sucessfully using the following config on package.json
```
    "overrides": {
        "@eventcatalog/core": {
            "swagger-ui-react": "5.10.5"
        }
    }
```

`swagger-ui-react` updated a version 5 days ago

**Comment by explorer14** [comment]
> I had the same issue. Just start and build sucessfully using the following config on package.json
> 
> ```
>     "overrides": {
>         "@eventcatalog/core": {
>             "swagger-ui-react": "5.10.5"
>         }
>     }
> ```
> 
> `swagger-ui-react` updated a version 5 days ago

The OP has already tried the overrides approach:

>Have tried solving version conflicts using overrides

As have I, it doesn't seem to change anything, the error still occurs.

**Comment by emyklebost** [comment]
> > I had the same issue. Just start and build sucessfully using the following config on package.json
> > ```
> >     "overrides": {
> >         "@eventcatalog/core": {
> >             "swagger-ui-react": "5.10.5"
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `swagger-ui-react` updated a version 5 days ago
> 
> The OP has already tried the overrides approach:
> 
> > Have tried solving version conflicts using overrides
> 
> As have I, it doesn't seem to change anything, the error still occurs.

Try deleting `package-lock.json` and `node_modules`. Apply the fix suggested by @mnlc, run `npm install` followed by `npm run build`.

**Comment by boyney123** [comment]
Thank you for your patience everyone, and the proposed solution folks. I have locked in the version of the swagger component for now, until we can figure out how we can upgrade this in future. 

This should get the build working again, new version updated `@eventcatalog/core@1.1.2`

[Upgrade your catalog](https://www.eventcatalog.dev/docs/guides/upgrading)
