### ISSUE TITLE
Changelog page always shows "EmailSent" as title

### ISSUE THREAD

**Issue by otbe** [boyney123/eventcatalog#81]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/boyney123/eventcatalog/blob/master/CONTRIBUTING.md#reporting-new-issues).

### Description

Changelog page always shows "EmailSent" as title

### Steps to reproduce

Statrting from `npx @eventcatalog/create-eventcatalog@latest my-catalog` and have a look at AddedItemToCart

### Expected behavior

Should show the name of the event .

### Actual behavior

Shows a static "EmailSent" event name. Its also in the docs.
https://eventcatalog.dev/docs/events/versioning

### Your environment

- EventCatalog version used: 0.0.8

**Comment by boyney123** [comment]
Thank you @otbe for raising the issue, will take a look!

**Comment by boyney123** [comment]
Fixed in `@eventcatalog/core@0.0.9`

Thank you @otbe !
